services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    command:
      - "sleep"
      - "infinity"
    depends_on:
      - search-parser

  search-parser:
    build:
      context: ./search-parser-service
      dockerfile: Dockerfile
      args:
        - MLIBRARY_SEARCH_PARSER_GIT=${MLIBRARY_SEARCH_PARSER_GIT:-https://github.com/mlibrary/mlibrary_search_parser.git}
        - MLIBRARY_SEARCH_PARSER_REF=${MLIBRARY_SEARCH_PARSER_REF:-DOR-159/opensearch-query-dsl}
    environment:
      - QUERY_FIELDS=${QUERY_FIELDS:-ic_all}
    ports:
      - "4567:4567"
    volumes:
      - ./search-parser-service:/app
    restart: unless-stopped
