services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      - OPENSEARCH_URL="https://opensearch.discovery.dor.lib.umich.edu"
      - OPENSEARCH_CREDENTIALS="admin:DiscOvery0!234dawg"
      - REACTIVESEARCH_URL="https://reactivesearch.discovery.dor.lib.umich.edu"
      - REACTIVESEARCH_CREDENTIALS="rs-admin-user:rs-password"
    command:
      - "sleep"
      - "infinity"
